theme: jekyll-theme-minimal
title: Louie Aroy
description: This site showcases all my projects for 6 years working as a software developer.
avatar: "https://avatars.githubusercontent.com/u/13733633?s=460&u=4106d567a5686bc43063f64592c845ec7e68783a&v=4"
round-avatar: true
