theme: jekyll-theme-minimal
title: Louie Aroy
description: Game Developer, Software Developer, CTO
logo: "https://avatars.githubusercontent.com/u/13733633?s=460&u=4106d567a5686bc43063f64592c845ec7e68783a&v=4"
